### ISSUE TITLE
bug report for even_odd_site.py

### ISSUE THREAD

**Issue by jwmahone** [Eric-Edlund/Open-Source-Repo#14]
// Changed for in range loop to while loop on line 7
// Changed if statment from == to != on line 8

**Comment by sizsak** [comment]
Changed the while loop to a for loop in range(50) line 8
Changed the =! to a == line 9

**Comment by sizsak** [comment]
Changed the while loop to a for loop in range(50) line 8
Changed the =! to a == line 9
