### ISSUE TITLE
sum_even_fibonacci.java bug report 

### ISSUE THREAD

**Issue by tasthana** [Eric-Edlund/Open-Source-Repo#18]
The bug is that the division of b, the variable that sees if the sequence is even by dividing it by 2, actually divides by 3 within an if loop. 

Steps to Reproduce

First step to reproduce the issue/bug
- Run the program 
Second step to reproduce the issue/bug
- Change 2 to 3 
Third step to reproduce the issue/bug
- not needed 
Expected Behavior A clear and concise description of what you expected to happen.
- The programs should have run and outputted the right answer, which would be even. 

Actual Behavior A clear and concise description of what actually happened.
- The 3 truncates so that the number that will be output will not be even, which is wrong. 

Screenshots If applicable, add screenshots to help explain the issue/bug.

Additional Information

Operating System: Mac OS Big Sur 
Browser: Safari
Version: 
Any other relevant information
Possible Solution If you have any suggestions for a possible solution, please include them here.
- Change the 3 to a 2

Related Issues Are there any related issues? If so, please link to them here.

Priority How critical is this issue/bug? Low, medium, or high priority?
- low priority 

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
- always be reproduced 
Impact What is the impact of this issue/bug? Low, medium, or high?
- high impact since it ruins the point of the function.

**Comment by dfisher5** [comment]
Updated loop to mod by 2 instead of 3.
