### ISSUE TITLE
remove_duplicates.java doesn't compile

### ISSUE THREAD

**Issue by Eric-Edlund** [Eric-Edlund/Open-Source-Repo#19]
There's this symbol `k` which appears in the file but is never defined. The list is also never sorted.

Steps to Reproduce

1) Try to compile the program

Actual Behavior:

The program doesn't compile

The program doesn't compile, making everything useless.

**Comment by DremmyII** [comment]
I fixed the issue by removing the variable k, replacing it with i (loop incrementor) in the code.

The list is still not sorted but that is fine because that's not what this program is supposed to do.
