### ISSUE TITLE
even_odd_site.cc

### ISSUE THREAD

**Issue by dfisher5** [Eric-Edlund/Open-Source-Repo#21]
Description Program does not compile.

Steps to Reproduce

First step Run program.
Expected Behavior Should print numbers from file sorted by even/odd.

Actual Behavior Compiler error.

Operating System: Windows
Browser: Google Chrome
Possible Solution In for loop, change i+ to i++ to increment the loop.

Priority High priority

Reproducibility Always

**Comment by Eric-Edlund** [comment]
Fixed it
