### ISSUE TITLE
sum_even_fibonacci.py bug report 

### ISSUE THREAD

**Issue by tasthana** [Eric-Edlund/Open-Source-Repo#22]
Description : 
- Initialized sum_even to 4000000 instead of 0.
- the while loop condition checks if b is more than 4000000.
- doesn't do the calculation of sum_even inside the loop to accumulate even Fibonacci numbers.
- doesn't do the assignment of an and b to calculate the next Fibonacci number correctly.

Steps to Reproduce
First step to reproduce the issue/bug
- initialize to wrong number 
- mess it all up 

Second step to reproduce the issue/bug
- rahhhh
Third step to reproduce the issue/bug

Expected Behavior A clear and concise description of what you expected to happen.
- should've worked properly 
- 
Actual Behavior A clear and concise description of what actually happened.
- doesn't work properly 
- 
Screenshots If applicable, add screenshots to help explain the issue/bug.

Additional Information

Operating System: Mac OS Big Sur
Browser: Safari
Version:
Any other relevant information

Possible Solution If you have any suggestions for a possible solution, please include them here.
Fix it by flipping the 4mil and zero, fix the calculation and assignment 
Related Issues Are there any related issues? If so, please link to them here.

Priority How critical is this issue/bug? Low, medium, or high priority?
- medium 
Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
- always 
Impact What is the impact of this issue/bug? Low, medium, or high?
-high

**Comment by dfisher5** [comment]
Initialized sum_even to 0. Other issues don't seem to be causing a problem.
